# Makefile automatically generated by ghdl
# Version: GHDL 4.1.0 (Ubuntu 4.1.0+dfsg-0ubuntu2.1) [Dunoon edition] - static elaboration, mcode JIT code generator
# Command used to generate this makefile:
# /usr/bin/ghdl-mcode --gen-makefile --ieee=synopsys -fexplicit --workdir=WORK testbench

GHDL=/usr/bin/ghdl-mcode
GHDLFLAGS= --ieee=synopsys -fexplicit --workdir=WORK
GHDLRUNFLAGS=

# Default target : elaborate
all : elab

# Elaborate target.  Almost useless
elab : force
	$(GHDL) -c $(GHDLFLAGS) -e testbench

# Run target
run : force
	$(GHDL) -c $(GHDLFLAGS) -r testbench $(GHDLRUNFLAGS)

# Targets to analyze libraries
init: force
	# /usr/lib/ghdl/mcode/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164.vhdl
	# /usr/lib/ghdl/mcode/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164-body.vhdl
	# /usr/lib/ghdl/mcode/vhdl/ieee/v93/../../src/ieee/v93/numeric_std.vhdl
	# /usr/lib/ghdl/mcode/vhdl/ieee/v93/../../src/ieee/v93/numeric_std-body.vhdl
	$(GHDL) -a $(GHDLFLAGS) testbench_AOC2_SoC_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) AOC2_SoC_2026.vhd
	# /usr/lib/ghdl/mcode/vhdl/ieee/v93/../../src/synopsys/std_logic_arith.vhdl
	# /usr/lib/ghdl/mcode/vhdl/ieee/v93/../../src/synopsys/std_logic_unsigned.vhdl
	$(GHDL) -a $(GHDLFLAGS) IO_MD_subsystem_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) INCOMPLETE_Mips_segmentado_IRQ_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) RAM_128_32_P1_tests_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) REGISTER.vhd
	$(GHDL) -a $(GHDLFLAGS) adder32.vhd
	$(GHDL) -a $(GHDLFLAGS) RAM_I_test_exceptions_neuron_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) Banco_ID.vhd
	$(GHDL) -a $(GHDLFLAGS) BReg.vhd
	$(GHDL) -a $(GHDLFLAGS) Ext_signo.vhd
	$(GHDL) -a $(GHDLFLAGS) bits_shifter.vhd
	$(GHDL) -a $(GHDLFLAGS) INCOMPLETE_UC_Mips_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) INCOMPLETE_UD_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) Banco_EX.vhd
	$(GHDL) -a $(GHDLFLAGS) INCOMPLETE_UA_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) mux4_1.vhd
	$(GHDL) -a $(GHDLFLAGS) mux2_1.vhd
	$(GHDL) -a $(GHDLFLAGS) ALU_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) mux2_5bits.vhd
	$(GHDL) -a $(GHDLFLAGS) Banco_MEM.vhd
	$(GHDL) -a $(GHDLFLAGS) Exception_manager.vhd
	$(GHDL) -a $(GHDLFLAGS) Banco_WB.vhd
	$(GHDL) -a $(GHDLFLAGS) counter.vhd

force:
